### ISSUE TITLE
`strict` on Send API?

### ISSUE THREAD

**Issue by FabioFleitas** [sendwithus/docs#41]
Does the Send API have a way to fail on missing template data similar to how the Render API works with the `strict` param? If not, I think it would be a useful addition.

**Comment by bvanvugt** [comment]
Hey @FabioFleitas, thanks for the suggestion! You're correct that it doesn't exist on the Send API -- we currently aren't built to support that, but I agree it would be useful. I'll make sure our product team takes it into consideration :)
